### PR TITLE
Fix:  Handle parsing error in proxyGroupsDagSort

### LINKED ISSUE #291: panic: interface conversion: interface {} is map[interface {}]interface {}, not string
panic: interface conversion: interface {} is map[interface {}]interface {}, not string

goroutine 1 [running]:
github.com/Dreamacro/clash/config.proxyGroupsDagSort(0xdc69c0, 0x8, 0x8, 0x16, 0xc28088)
	/home/travis/gopath/src/github.com/frainzy1477/clash_dev/config/utils.go:78 +0x16c0
github.com/Dreamacro/clash/config.parseProxies(0xc9a0a0, 0xc68370, 0x0, 0x0)
	/home/travis/gopath/src/github.com/frainzy1477/clash_dev/config/config.go:296 +0x8d0
github.com/Dreamacro/clash/config.Parse(0xc1a4c0, 0x16, 0x2, 0xc1a4c0, 0x16)
	/home/travis/gopath/src/github.com/frainzy1477/clash_dev/config/config.go:170 +0xe0
github.com/Dreamacro/clash/hub/executor.ParseWithPath(...)
	/home/travis/gopath/src/github.com/frainzy1477/clash_dev/hub/executor/executor.go:21
github.com/Dreamacro/clash/hub/executor.Parse(0xa, 0x4fab37, 0xb)
	/home/travis/gopath/src/github.com/frainzy1477/clash_dev/hub/executor/executor.go:16 +0xb0
github.com/Dreamacro/clash/hub.Parse(0x7fd29b5e, 0xa)
	/home/travis/gopath/src/github.com/frainzy1477/clash_dev/hub/hub.go:10 +0x34
main.main()
	/home/travis/gopath/src/github.com/frainzy1477/clash_dev/main.go:51 +0x188

wndr 3700v4
openwrt 18.04
貌似是解json出错？

### PR DESCRIPTION
**Pull request by comzyh**
Fix #291

### CODE REVIEW

File: config/utils.go [hunk 1]
```diff
@@ -51,14 +52,27 @@ func proxyGroupsDagSort(groupsConfig []map[string]interface{}) error {
 		from      []string
 	}
 
+	type ProxyGroupOption struct {
```
Comment (Dreamacro) [inline config/utils.go]: In principle, the struct is not defined in a function

File: config/utils.go [hunk 2]
```diff
@@ -51,14 +52,27 @@ func proxyGroupsDagSort(groupsConfig []map[string]interface{}) error {
...
+		Name    string   `proxy:"name"`
+		Proxies []string `proxy:"proxies"`
+	}
+
 	graph := make(map[string]*Node)
 
 	// Step 1.1 build dependency graph
 	for idx, mapping := range groupsConfig {
+
 		groupName, existName := mapping["name"].(string)
```
Comment (Dreamacro) [inline config/utils.go]: why not decode at the top of `for`?

Comment (comzyh) [reply config/utils.go]: I'm afraid that if decode failed because of `proxies` field, we can't get the Name field either.

I'm not familiar with Go reflection. But base on my test, this depends on the order of `Name` and `Proxies` field in ProxyGroupOption.

If I change the definition of ProxyGroupOption to 
```type ProxyGroupOption struct {
		Proxies []string `proxy:"proxies"`
		Name    string   `proxy:"name"`
	}
```
I can use `option.Name` to get the proxy group name, and can not return the correct error log i.

Comment (Dreamacro) [reply config/utils.go]: `groupName, existName := mapping["name"].(string)` skip the validate of name, and lead the crash when `mapping["name"]` is nil

Comment (comzyh) [reply config/utils.go]: ok, using the decoder to do this is always better.

File: config/utils.go (hunk 1 above)
Comment (comzyh) [reply config/utils.go]: Yes, I agree with you on that. What's your suggestion?

Comment (Dreamacro) [reply config/utils.go]: put `ProxyGroupOption` into adapter, and put `node` out of this function

File: config/utils.go [hunk 3]
```diff
@@ -51,14 +52,23 @@ func proxyGroupsDagSort(groupsConfig []map[string]interface{}) error {
...
+
 	graph := make(map[string]*Node)
 
 	// Step 1.1 build dependency graph
-	for idx, mapping := range groupsConfig {
-		groupName, existName := mapping["name"].(string)
-		if !existName {
-			return fmt.Errorf("ProxyGroup %d: missing name", idx)
+	for _, mapping := range groupsConfig {
+
```
Comment (Dreamacro) [inline config/utils.go]: empty line?

**Comment by comzyh** [comment]
Thanks for editing :+1:
